### ISSUE TITLE
Crashing in VMWare 15

### ISSUE THREAD

**Issue by kozera2137** [wbenny/hvpp#16] opened 2018-10-09 18:20 UTC
Hi. I have installed the newest available version of VMWare and it seems to be crashing at the moment of entering VMX mode. I hadn't any problems with older version of VMWare that supported only Workstation 14.x, now it doesn't want to work even with Workstation 12.x. Anyone knows how to solve it?
![lol](https://user-images.githubusercontent.com/42409418/46689697-c14e4a80-cc00-11e8-98dc-77fb0d94d29c.png)

**Comment by wbenny** [comment] 2018-10-09 18:44
Hi, I've got the same problem on VMware 15, and it appears it affects other hypervisors as well. Unfortunatelly, I didn't dig deep into what causes this problem, mainly because I currently have only licence to VMware 14 (which I switched back to) and I need it to work for my other projects.

**Comment by rianquinn** [comment] 2018-10-09 18:47
That's strange. Bareflank is currently working fine on the latest VMWare Fusion and VMWare Workstation.

**Comment by tandasat** [comment] 2018-10-10 01:38
My project has the same issue with VMware 15. With quick tests, I see that:
- First VM-exit (it is CPUID in my case) triggers hypervisor code as expected
- After VMRESUME, VMware crashes, without triggering the any further VM-exit (so appears to be VM-entry emulation related issue)
- It has no impact to disable EPT and some other optional VM-exits
- It has no impact to make the VM single core
- It has no impact to disable those two options
![image](https://user-images.githubusercontent.com/1620923/46708114-f43d1200-cbf1-11e8-9910-538288079c76.png)

Only tested with x64 Windows 10 RS4 at this point. I do not have a license either but still has VMware 15 under the trial license at this moment.

**Comment by rianquinn** [comment] 2018-10-10 12:27
I have not tried on Windows 10 yet (we mostly dev on Linux and then test on Windows with real hardware). I'll give it s shot and report back to see if Bareflank sees the same issue on Windows

**Comment by wbenny** [comment] 2018-10-10 12:33
Interesting. I'm starting to think it might be related to Hyper-V Enlightenments... again :)

**Comment by tandasat** [comment] 2018-10-10 15:04
Cannot conclude it is unrelated, but at least the values of nt!Hvl(s)Enlightenments are the same between a VM on 14 and 15 (ie, 00002120), so seems unlikely.

**Comment by DiskGetor** [comment] 2018-10-11 09:38
![sx cy2z4 4iz41 nkrp n](https://user-images.githubusercontent.com/19886504/46795171-12367e00-cd7c-11e8-8ce7-a75c52822f1f.png)
![image](https://user-images.githubusercontent.com/19886504/46795221-2da18900-cd7c-11e8-95ef-3244f3f4cc2f.png)
[VMware15 KeyGen.zip](https://github.com/wbenny/hvpp/files/2468310/VMware15.KeyGen.zip)

**Comment by tandasat** [comment] 2018-10-12 15:06
Noticed that VMRESUME completed and the guest ran OK for few moments. Then it dies without the triggering any further VM-exits.

**Comment by tandasat** [comment] 2018-10-12 15:20
@kozera2137 does this reproduce on Windows 7 as well?

**Comment by rianquinn** [comment] 2018-10-17 12:15
Sorry, I haven't had a chance to test on my end yet (I hope to do that this weekend), been very busy. But I was thinking. If this does end up being a widespread issue, I wonder if VMWare's L1TF additions broke their nested support. Specifically, I know that one of the mods that had to be made to fix L1TF was to add an L1 cache flush just before VMRESUME. 

Just a thought.

**Comment by tandasat** [comment] 2018-10-17 12:47
VMware is breaking other hypervisors and on ESXi as well. 
https://communities.vmware.com/message/2809089#2809089

I had to uninstall the v15, but anyone might be able to test with VMware Player. I expect they share the same issue.

**Comment by rianquinn** [comment] 2018-10-17 13:02
Huh... that's good to know. What's strange is this is not an issue with Linux. That is, I am using the latest versions of both VMWare Workstation Pro and VMWare Fusion with Linux without an issue, and we are even working on guest support right now so I am trapping on interrupts and working with more than one VMCS per CPU without any issues. 

Pretty strange. Either way, I will test this when I get a chance and report back.

**Comment by rianquinn** [comment] 2018-11-12 21:17
Well, I have been able to replicate the issue with VMWare Fusion 11 and Bareflank on Windows 10. The issue doesn't happen in Linux, but it does happen on Windows 10. I have no idea why.

As far as I can tell, nested virtualization on Windows with VMWare is completely broken. Any updates on this?

**Comment by how02** [comment] 2018-11-23 17:45
Looks like the issue has been resolved in VMware Workstation 15.0.2

**Comment by wbenny** [comment] 2018-11-23 18:03
@how02 Thank you, thats great news. Can at least one more person confirm this? I'd close this issue after that.

**Comment by tandasat** [comment] 2018-11-24 00:21
@wbenny Yep, confirmed it has been resolved. Tested on Win10 + Workstation 15.0.2.

**Comment by wbenny** [comment] 2018-11-24 10:54
Much appreciated!

**Closed as completed by wbenny** 2018-11-24 10:54 UTC
Labels: help wanted

**Comment by rianquinn** [comment] 2018-11-24 13:43
Woot!!! This is awesome news. Thanks for tracking this
